### PR TITLE
Update deps, and simplify SCF code a bit

### PR DESCRIPTION
**Pull request by antoine-levitt**
Simplify the SCF code thanks to the NLsolve release. I also changed the order of tests a bit so it's more convenient when breaking stuff.

### CODE REVIEW

**Comment by mfherbst** [comment]
I agree with all, but the change of the test order. The problem here is that as of now Julia aborts any testing as soon as one test case fails, so if first the "building blocks" are tested and then the full thing, you know which building block failed. Otherwise you only know that something is wrong.

If you did this to get faster feedback on Travis, I suggest to split the test suite into unit tests and functionality tests and run the functionality tests first and the unit tests afterwards, but configure in a way that for sure both are run. That way you get a fast failure and feedback what went wrong.

I'm happy to do that ... it involves a little playing with the CI.

By the way: Last PR to merge before we'll move to JuliaMolSim :smile:.

**Comment by antoine-levitt** [comment]
I did it to get faster feedback when ] test DFTK. Is there any way to just run all the tests even when one of them fail? At worse can just do it ourselves with a macro that does a try catch, but there should be a nicer way...

**Comment by mfherbst** [comment]
I see. Not a fan of the macro, that's not such a clean solution. Instead I think what one can do is simply to use an environment variable to influence the test order. If it's set, than the big tests run first, otherwise not.

**Comment by antoine-levitt** [comment]
See https://stackoverflow.com/questions/48628549/about-the-right-way-to-use-julia-base-test-run-all-tests-even-if-some-fail. So we just wrap everything with `@testset "All tests"`. Then we get a full report from CI, but it's more convenient to test interactively. Is that OK?

**Comment by mfherbst** [comment]
Then I'm ok, if you move the full paragraph of "big tests" up ... I see no reason why PBE is special.

**Comment by antoine-levitt** [comment]
The point was to just get one (I took PBE because it was the "most complicated") to get a fast diagnostic. I'll move them up.

**Pull request merged**
